/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface AppHeader {
    }
    interface AppNav {
    }
    interface AppPageAboutMe {
    }
    interface AppPageHome {
    }
    interface AppPageRoot {
    }
}
declare global {
    interface HTMLAppHeaderElement extends Components.AppHeader, HTMLStencilElement {
    }
    var HTMLAppHeaderElement: {
        prototype: HTMLAppHeaderElement;
        new (): HTMLAppHeaderElement;
    };
    interface HTMLAppNavElement extends Components.AppNav, HTMLStencilElement {
    }
    var HTMLAppNavElement: {
        prototype: HTMLAppNavElement;
        new (): HTMLAppNavElement;
    };
    interface HTMLAppPageAboutMeElement extends Components.AppPageAboutMe, HTMLStencilElement {
    }
    var HTMLAppPageAboutMeElement: {
        prototype: HTMLAppPageAboutMeElement;
        new (): HTMLAppPageAboutMeElement;
    };
    interface HTMLAppPageHomeElement extends Components.AppPageHome, HTMLStencilElement {
    }
    var HTMLAppPageHomeElement: {
        prototype: HTMLAppPageHomeElement;
        new (): HTMLAppPageHomeElement;
    };
    interface HTMLAppPageRootElement extends Components.AppPageRoot, HTMLStencilElement {
    }
    var HTMLAppPageRootElement: {
        prototype: HTMLAppPageRootElement;
        new (): HTMLAppPageRootElement;
    };
    interface HTMLElementTagNameMap {
        "app-header": HTMLAppHeaderElement;
        "app-nav": HTMLAppNavElement;
        "app-page-about-me": HTMLAppPageAboutMeElement;
        "app-page-home": HTMLAppPageHomeElement;
        "app-page-root": HTMLAppPageRootElement;
    }
}
declare namespace LocalJSX {
    interface AppHeader {
    }
    interface AppNav {
    }
    interface AppPageAboutMe {
    }
    interface AppPageHome {
    }
    interface AppPageRoot {
    }
    interface IntrinsicElements {
        "app-header": AppHeader;
        "app-nav": AppNav;
        "app-page-about-me": AppPageAboutMe;
        "app-page-home": AppPageHome;
        "app-page-root": AppPageRoot;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "app-header": LocalJSX.AppHeader & JSXBase.HTMLAttributes<HTMLAppHeaderElement>;
            "app-nav": LocalJSX.AppNav & JSXBase.HTMLAttributes<HTMLAppNavElement>;
            "app-page-about-me": LocalJSX.AppPageAboutMe & JSXBase.HTMLAttributes<HTMLAppPageAboutMeElement>;
            "app-page-home": LocalJSX.AppPageHome & JSXBase.HTMLAttributes<HTMLAppPageHomeElement>;
            "app-page-root": LocalJSX.AppPageRoot & JSXBase.HTMLAttributes<HTMLAppPageRootElement>;
        }
    }
}
